### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Peech
email: info@peechapp.co
description: Text to speech
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://peechapp.co" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#1da1ab'
logo: assets/images/large_logo.png
social:
  name: Peech
  links:
    - https://www.facebook.com/peechapp
    - https://instagram.com/peech.app
    - https://www.tiktok.com/@peech.app
languages: ["en"]
ampdir: amp

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - package-lock.json
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
  - tracking_cta_page
